export const Colors = {
  Primary: "#2a4a6d",
  Secondary: "#3677bd",
  Tertiary: "#48aaff",
  Accent: "#ab68ff",
  BackgroundRoot: "#000",
  BackgroundPrimary: "#212121e6",
  BackgroundSecondary: "#b3b3b3",
  TextPrimary: "#ececec",
  TextSecondary: "#ffffffb3",
  TextTertiary: "#ffffff94",
  TextQuaternary: "#ffffff69",
  TextPlaceholder: "#fffc",
  Transparent: "#00000000",
  Danger: "#f93a37",
  Icon: "#f0f0f0",
  White: "#fff",
  Black: "#000",
  Link: "#7ab7ff",
  LinkHover: "#5e83b3",
  BorderXlight: "#ffffff0d",
  BorderLight: "#ffffff1a",
  BorderMedium: "#ffffff26",
  BorderHeavy: "#fff3",
  BorderXheavy: "#ffffff40",
  BorderSharp: "#ffffff0d",
} as const;
