name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - name: Install dependencies
        # Like npm install but deletes node_modules first and install exactly lockfile deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: TypeScript type check
        # Check types. noEmit for NOT producing JS output
        run: npm run check-types
      - name: Code style check
        run: npm run prettier
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
